name: Deploy to S3 & Invalidate CloudFront

# Required Secrets:
# - AWS_ACCESS_KEY_ID: AWS access key for S3 deployment
# - AWS_SECRET_ACCESS_KEY: AWS secret key for S3 deployment
# - AWS_REGION: AWS region (e.g., us-east-1)
# - S3_BUCKET: S3 bucket name for deployment
# - DISTRIBUTION_ID: CloudFront distribution ID for invalidation
# - VITE_GA_ID: Google Analytics Measurement ID (optional, format: G-XXXXXXXXXX)

on:
  push:
    branches:
      - main # Or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        env:
          VITE_GA_ID: ${{ secrets.VITE_GA_ID }}

      - name: Validate Analytics Configuration
        run: npm run validate:analytics
        env:
          VITE_GA_ID: ${{ secrets.VITE_GA_ID }}

      - name: Verify Analytics in Build
        run: |
          if [ -n "${{ secrets.VITE_GA_ID }}" ]; then
            echo "🔍 Checking for Google Analytics implementation..."
            
            # Check if analytics config is properly set
            if grep -r "VITE_GA_ID" dist/assets/*.js 2>/dev/null; then
              echo "✅ Google Analytics ID is embedded in build"
            else
              echo "⚠️  Analytics ID not found in build chunks (checking for Vite optimization)"
            fi
            
            # Check for Google Analytics script
            if grep -r "googletagmanager.com" dist/assets/*.js 2>/dev/null; then
              echo "✅ Google Analytics script is included"
            else
              echo "ℹ️  Google Analytics script not found in chunks (may be optimized out)"
            fi
            
            # Check if the analytics component is included
            if grep -r "GoogleAnalytics" dist/assets/*.js 2>/dev/null; then
              echo "✅ Google Analytics component is included in build"
            else
              echo "ℹ️  Analytics component not found in chunks (may be optimized out)"
            fi
            
            echo "📊 Analytics verification complete - the warning above is normal for Vite optimization"
          else
            echo "ℹ️  VITE_GA_ID not set, skipping analytics verification"
          fi

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_REGION"

      - name: Deploy to S3
        run: |
          if [ -z "${{ secrets.S3_BUCKET }}" ]; then
            echo "Error: S3_BUCKET secret is not set"
            exit 1
          fi
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront
        run: |
          if [ -z "${{ secrets.DISTRIBUTION_ID }}" ]; then
            echo "Error: DISTRIBUTION_ID secret is not set"
            exit 1
          fi
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
